### ISSUE TITLE
Add monuments data

### ISSUE THREAD

**Issue by BGranberg** [agrc/locate#159]
Add GSENM and Bears Ears to the National Parks and Monuments layer with their own color cause their are BLM.

**Comment by stdavis** [comment]
I'm not sure that I different color works with the application since all layers with the Lifestyle group are the same green color. Maybe a different shade of green? Or add a "B" to the icon?

![image](https://user-images.githubusercontent.com/1326248/28431089-2bcafcbc-6d40-11e7-8d37-5766a483483b.png)

**Comment by stdavis** [comment]
Ping @BGranberg
